name: Build and Test

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish .NET 9 artifacts
      run: dotnet publish -c Release -f net9.0 -o ./publish/net9
      continue-on-error: true

    - name: Publish .NET 8 artifacts
      run: dotnet publish -c Release -f net8.0 -o ./publish/net8
      continue-on-error: true

    - name: Upload .NET 9 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-net9
        path: ./publish/net9

    - name: Upload .NET 8 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-net8
        path: ./publish/net8

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Download .NET 9 artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts-net9
        path: ./publish/net9

    - name: Download .NET 8 artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts-net8
        path: ./publish/net8

    - name: Run all tests
      run: dotnet test ./publish/**/CarrotMQ*Test*.dll --verbosity normal