name: Build and Test

on:
  workflow_call:
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build  -c Release --no-restore

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-net
        path: |
            ./CarrotMQ.*/bin/Release/
            !./CarrotMQ.*/bin/Release/net472

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts-net

    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Run all tests
      run: dotnet test ./**/CarrotMQ*Test*.dll --verbosity normal