name: publish-nugets

on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build CarrotMQ.Core (Release)
        run: dotnet build ${{ github.workspace }}\CarrotMQ.Core\CarrotMQ.Core.csproj --configuration=Release

      - name: Build CarrotMQ.RabbitMQ (Release)
        run: dotnet build ${{ github.workspace }}\CarrotMQ.RabbitMQ\CarrotMQ.RabbitMQ.csproj --configuration=Release
      
      - name: Publish to NuGet
        run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source 'https://api.nuget.org/v3/index.json' ${{ github.workspace }}\packages\CarrotMQ.*.nupkg